/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Clases.myTableModel;
import java.util.ArrayList;
import javax.swing.JTable;

/**
 *
 * @author elearning02
 */
public class viLista extends javax.swing.JInternalFrame {
    private myTableModel m;
    private ArrayList columnIdentifiers;
    /**
     * Creates new form viLista
     */
    public viLista() {
        initComponents();
        columnIdentifiers = new ArrayList();
        columnIdentifiers.add("Código");
        columnIdentifiers.add("Descripción");
        columnIdentifiers.add("Cantidad");        
        
        Object[][] data;
        data = new Object[][] {
            { "0", " ", new Float(0) },
            { "0", " ", new Float(0) } };

        this.m = new myTableModel(columnIdentifiers, data);
        // create the data model and the JTable
        JTable table = new JTable(this.m);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollLista = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manejo de tabla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollLista, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jScrollLista, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollLista;
    // End of variables declaration//GEN-END:variables
}
